#!/usr/bin/env python3
"""Emit the real FlyWire PN->KC wiring as an ES module the toy can import.

Source: FlyWire release 783 (CC-BY-4.0), extracted by ../../extract_mb_circuit.py.
Output: ../flywire_pn_kc.mjs -- a plain ESM export so Node tests and the browser
load it identically, with no fetch and no async in OdorBrain's constructor.

Root IDs exceed Number.MAX_SAFE_INTEGER, so they ship as strings. They are
reference only; the edge list is index-based.
"""
import json, pathlib, sys
import pandas as pd

HERE = pathlib.Path(__file__).resolve().parent
CACHE = HERE.parent.parent                      # data/flywire
OUT = HERE.parent / "flywire_pn_kc.mjs"

HEMISPHERE = "right"
MIN_SYNAPSES = 3

nodes = pd.read_parquet(CACHE / "mb_circuit_nodes.parquet")
edges = pd.read_parquet(CACHE / "mb_circuit_edges.parquet")

side = nodes[nodes.side == HEMISPHERE]
pns = side[side.stage == "uPN"].sort_values("root_id").reset_index(drop=True)
kcs = side[side.stage == "KC"].sort_values("root_id").reset_index(drop=True)

pn_ix = {r: i for i, r in enumerate(pns.root_id)}
kc_ix = {r: i for i, r in enumerate(kcs.root_id)}

pk = edges[edges.pre_pt_root_id.isin(pn_ix) & edges.post_pt_root_id.isin(kc_ix)]
# One row per neuropil in the source; sum them into a single connection weight.
agg = (pk.groupby(["pre_pt_root_id", "post_pt_root_id"], as_index=False)
         .syn_count.sum())
agg = agg[agg.syn_count >= MIN_SYNAPSES].sort_values(
    ["pre_pt_root_id", "post_pt_root_id"])

edge_pn = [pn_ix[r] for r in agg.pre_pt_root_id]
edge_kc = [kc_ix[r] for r in agg.post_pt_root_id]
edge_syn = [int(s) for s in agg.syn_count]

glomerulus = [str(t) if pd.notna(t) else "" for t in pns.cell_type]
subclass = [str(s) if pd.notna(s) else "" for s in kcs.cell_sub_class]
orphans = len(kcs) - len(set(edge_kc))

meta = {
    "source": "FlyWire release 783 (Dorkenwald et al. 2024; Schlegel et al. 2024)",
    "license": "CC-BY-4.0",
    "hemisphere": HEMISPHERE,
    "min_synapses": MIN_SYNAPSES,
    "n_pn": len(pns),
    "n_kc": len(kcs),
    "n_edges": len(edge_pn),
    "n_glomeruli": int(pns.cell_type.nunique()),
    "kcs_without_pn_input": orphans,
    "mean_pns_per_kc": round(len(edge_pn) / max(1, len(set(edge_kc))), 3),
}

def arr(x):
    return json.dumps(x, separators=(",", ""))

OUT.write_text(f"""// GENERATED by scripts/build_flywire_pn_kc.py -- do not edit by hand.
// Real PN->KC connectivity, FlyWire release 783, CC-BY-4.0.
// Root IDs are strings: they exceed Number.MAX_SAFE_INTEGER. Edges use indices.
export const FLYWIRE_PN_KC = Object.freeze({{
  meta: {json.dumps(meta, indent=2)},
  pnIds: {arr([str(r) for r in pns.root_id])},
  pnGlomerulus: {arr(glomerulus)},
  kcIds: {arr([str(r) for r in kcs.root_id])},
  kcSubclass: {arr(subclass)},
  edgePn: {arr(edge_pn)},
  edgeKc: {arr(edge_kc)},
  edgeSyn: {arr(edge_syn)},
}});
""")

print(json.dumps(meta, indent=2))
print(f"\nwrote {OUT}  ({OUT.stat().st_size / 1024:.0f} KB)")
if len(edge_pn) == 0:
    sys.exit("no edges emitted -- check the cache parquets")
