#!/usr/bin/env python3
"""Emit the mushroom body's real output layer: KC -> MBON weights, and each
MBON's valence sign DERIVED from anatomy rather than typed in by hand.

Two structural facts do the work, both present in FlyWire release 783:

  1. Which dopaminergic cluster writes to an MBON's compartment. The PAM
     cluster carries reward, the PPL1 cluster carries punishment. This is the
     classic anatomical split of the mushroom body and it is legible in the
     cell type names (PAM01.., PPL101..).

  2. The MBON's own transmitter. Acetylcholine excites its downstream targets;
     GABA and glutamate inhibit them in the fly.

An MBON whose compartment is written by reward DANs, and which excites what it
projects to, pushes toward approach. Flip either fact and the sign flips. That
is a claim about wiring, not a number someone chose.
"""
import json, pathlib
import pandas as pd

HERE = pathlib.Path(__file__).resolve().parent
CACHE = HERE.parent.parent
OUT = HERE.parent / "mb_output.mjs"
HEMISPHERE, MIN_SYNAPSES = "right", 3

nodes = pd.read_parquet(CACHE / "mb_circuit_nodes.parquet")
edges = pd.read_parquet(CACHE / "mb_circuit_edges.parquet")
side = nodes[nodes.side == HEMISPHERE]

kcs = side[side.stage == "KC"].sort_values("root_id").reset_index(drop=True)
mbons = side[side.stage == "MBON"].sort_values("root_id").reset_index(drop=True)
dans = side[side.stage == "DAN"]

kc_ix = {r: i for i, r in enumerate(kcs.root_id)}
mb_ix = {r: i for i, r in enumerate(mbons.root_id)}
dan_type = dict(zip(dans.root_id, dans.cell_type.fillna("")))


def agg(pre_ids, post_ids):
    e = edges[edges.pre_pt_root_id.isin(pre_ids) & edges.post_pt_root_id.isin(post_ids)]
    a = e.groupby(["pre_pt_root_id", "post_pt_root_id"], as_index=False).syn_count.sum()
    return a[a.syn_count >= MIN_SYNAPSES]


kc_mbon = agg(kc_ix, mb_ix)
dan_mbon = agg(set(dan_type), mb_ix)

# Reward vs punishment drive per MBON, straight from synapse counts.
rows = []
for r, i in mb_ix.items():
    d = dan_mbon[dan_mbon.post_pt_root_id == r]
    pam = ppl = 0
    for _, x in d.iterrows():
        t = dan_type.get(x.pre_pt_root_id, "")
        if t.startswith("PAM"):
            pam += x.syn_count
        elif t.startswith("PPL"):
            ppl += x.syn_count
    nt = str(mbons.loc[i, "top_nt"] or "")
    # acetylcholine excites downstream targets; GABA and glutamate inhibit.
    output_sign = 1 if nt == "acetylcholine" else -1 if nt in ("gaba", "glutamate") else 0
    # An appetitive compartment (PAM-dominated) depresses onto approach.
    total = pam + ppl
    dan_bias = (pam - ppl) / total if total else 0.0
    rows.append({
        "cell_type": str(mbons.loc[i, "cell_type"] or ""),
        "nt": nt, "output_sign": output_sign,
        "pam_syn": int(pam), "ppl1_syn": int(ppl),
        "dan_bias": round(dan_bias, 4),
        # Compartment identity ALONE sets the behavioural sign. Appetitive
        # training depresses KC->MBON synapses in PAM-written compartments, and
        # removing that output is what produces approach -- so a PAM-compartment
        # MBON drives AVOIDANCE while intact.
        #
        # The transmitter is recorded but deliberately NOT used here. Mapping a
        # transmitter onto approach or avoidance requires the downstream network
        # this extraction does not contain; folding it in made the sign depend on
        # an assumption rather than on anatomy, and left reward DECREASING value.
        "approach_drive": round(-dan_bias, 4),
    })

j = lambda x: json.dumps(x, separators=(",", ":"))
meta = {
    "source": "FlyWire release 783, CC-BY-4.0",
    "hemisphere": HEMISPHERE, "min_synapses": MIN_SYNAPSES,
    "n_kc": len(kcs), "n_mbon": len(mbons),
    "n_kc_mbon_edges": int(len(kc_mbon)),
    "n_dan_mbon_edges": int(len(dan_mbon)),
    "mbons_with_dan_input": int(sum(1 for r in rows if r["pam_syn"] + r["ppl1_syn"] > 0)),
    "derivation": "approach_drive = -dan_bias, where dan_bias is (PAM-PPL1)/(PAM+PPL1) "
                  "synapses onto the MBON. Transmitter is reported but not used for the sign. "
                  "No hand-set per-odor or per-glomerulus valence anywhere.",
}
OUT.write_text(f"""// GENERATED by scripts/build_mb_output.py -- do not edit by hand.
// Real KC->MBON wiring and an MBON valence axis DERIVED from which dopaminergic
// cluster writes to each compartment and what transmitter the MBON releases.
export const MB_OUTPUT = Object.freeze({{
  meta: {json.dumps(meta, indent=2)},
  mbons: {j([r["cell_type"] for r in rows])},
  nt: {j([r["nt"] for r in rows])},
  outputSign: {j([r["output_sign"] for r in rows])},
  danBias: {j([r["dan_bias"] for r in rows])},
  approachDrive: {j([r["approach_drive"] for r in rows])},
  pamSyn: {j([r["pam_syn"] for r in rows])},
  ppl1Syn: {j([r["ppl1_syn"] for r in rows])},
  edgeKc: {j([kc_ix[r] for r in kc_mbon.pre_pt_root_id])},
  edgeMbon: {j([mb_ix[r] for r in kc_mbon.post_pt_root_id])},
  edgeSyn: {j([int(s) for s in kc_mbon.syn_count])},
}});
""")
print(json.dumps(meta, indent=2))
print("\nMBON            nt              PAM   PPL1   bias   out  approach")
for r in sorted(rows, key=lambda r: -r["approach_drive"])[:10] + [None] + \
         sorted(rows, key=lambda r: r["approach_drive"])[:6]:
    if r is None:
        print("   ...")
        continue
    print(f'  {r["cell_type"]:14s} {r["nt"]:14s} {r["pam_syn"]:5d} {r["ppl1_syn"]:5d} '
          f'{r["dan_bias"]:+.2f} {r["output_sign"]:+3d}  {r["approach_drive"]:+.3f}')
print(f"\nwrote {OUT}  ({OUT.stat().st_size/1024:.0f} KB)")
