#!/usr/bin/env python3
"""Emit measured odorant -> glomerulus responses as an ES module.

Source: DoOR 2.0 (Munch & Galizia 2016), ropensci/DoOR.data, CC-BY.
These are electrophysiology and calcium-imaging measurements merged and
rescaled onto a common 0-1 axis -- not predicted, not docked, not modelled.

The chain is odorant -> Or gene -> OSN class -> glomerulus, and DoOR ships the
mapping. FlyWire uniglomerular PNs are named by their glomerulus, so the join
into the connectome is on that name.
"""
import csv, json, pathlib
import pandas as pd

HERE = pathlib.Path(__file__).resolve().parent
DOOR = HERE.parent.parent.parent / "door"
CACHE = HERE.parent.parent
OUT = HERE.parent / "door_responses.mjs"

MIN_ODORANTS_PER_GLOMERULUS = 30   # drop barely-measured channels
MIN_GLOMERULI_PER_ODORANT = 10     # an odorant needs a real activation pattern


def load(path):
    rows = list(csv.reader(open(path), delimiter=";"))
    return [dict(zip(["rowname"] + rows[0], r)) for r in rows[1:]], rows[0]


odor, _ = load(DOOR / "odor.csv")
rm, units = load(DOOR / "door_response_matrix.csv")
mappings, _ = load(DOOR / "door_mappings.csv")

meta_by_key = {o["InChIKey"]: o for o in odor}
n_measured = {u: sum(1 for r in rm if r[u] not in ("NA", "", None)) for u in units}

# glomerulus -> the best-measured DoOR column that reports it
glom_unit = {}
for m in mappings:
    g = m["glomerulus"]
    if g in ("", "?", None):
        continue
    for cand in (m["receptor"], m["OSN"], m["code.OSN"]):
        if cand in n_measured and n_measured[cand] > glom_unit.get(g, ("", 0))[1]:
            glom_unit[g] = (cand, n_measured[cand])

# keep only glomeruli that real FlyWire uniglomerular PNs actually target
nodes = pd.read_parquet(CACHE / "mb_circuit_nodes.parquet")
upn = nodes[(nodes.side == "right") & (nodes.stage == "uPN")]
wanted = sorted({g for g in upn.cell_type.fillna("").str.split("_").str[0] if g})

glomeruli = [g for g in wanted
             if g in glom_unit and glom_unit[g][1] >= MIN_ODORANTS_PER_GLOMERULUS]
cols = [glom_unit[g][0] for g in glomeruli]

# odorants with enough of those glomeruli measured
rows, names, cas, keys = [], [], [], []
for r in rm:
    vals = [None if r[c] in ("NA", "", None) else round(float(r[c]), 4) for c in cols]
    if sum(v is not None for v in vals) < MIN_GLOMERULI_PER_ODORANT:
        continue
    m = meta_by_key.get(r["rowname"])
    if not m or not m["Name"] or m["Name"] in ("sfr", "oil"):   # solvent/blank rows
        continue
    rows.append(vals)
    names.append(m["Name"])
    cas.append(m["CAS"] if m["CAS"] not in ("SFR", "") else "")
    keys.append(r["rowname"])

fill = sum(v is not None for row in rows for v in row) / (len(rows) * len(cols))
meta = {
    "source": "DoOR 2.0 (Munch & Galizia 2016), ropensci/DoOR.data",
    "license": "CC-BY",
    "measurement": "single-sensillum recording and calcium imaging, merged and "
                   "rescaled to a common 0-1 axis. Not predicted or docked.",
    "n_glomeruli": len(glomeruli),
    "n_odorants": len(rows),
    "min_odorants_per_glomerulus": MIN_ODORANTS_PER_GLOMERULUS,
    "min_glomeruli_per_odorant": MIN_GLOMERULI_PER_ODORANT,
    "matrix_fill": round(fill, 4),
    "note": "null means not measured, which is NOT the same as no response. "
            "Treat null as missing and say so; do not silently read it as zero.",
}

j = lambda x: json.dumps(x, separators=(",", ":"))
OUT.write_text(f"""// GENERATED by scripts/build_door_responses.py -- do not edit by hand.
// Measured odorant -> glomerulus responses. DoOR 2.0, CC-BY.
// responses[odorantIndex][glomerulusIndex]; null = not measured.
export const DOOR_RESPONSES = Object.freeze({{
  meta: {json.dumps(meta, indent=2)},
  glomeruli: {j(glomeruli)},
  doorUnit: {j(cols)},
  odorants: {j(names)},
  cas: {j(cas)},
  inchikeys: {j(keys)},
  responses: {j(rows)},
}});
""")

print(json.dumps(meta, indent=2))
print("\nglomeruli:", " ".join(f"{g}({u})" for g, u in zip(glomeruli, cols)))
print(f"\nwrote {OUT}  ({OUT.stat().st_size / 1024:.0f} KB)")
