import { chromium } from 'playwright';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { fileURLToPath } from 'node:url';
import { writeFile, stat } from 'node:fs/promises';
import assert from 'node:assert/strict';

const root = fileURLToPath(new URL('../', import.meta.url));
const server = spawn(process.execPath, ['server.mjs'], { cwd: root, env: { ...process.env, PORT: '4174' }, stdio: ['ignore', 'pipe', 'inherit'] });
let browser;
try {
  await once(server.stdout, 'data');
  browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1250 }, deviceScaleFactor: 1 });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()); });
  page.on('response', response => { if (response.status() >= 400) errors.push(`${response.status()} ${response.url()}`); });
  await page.goto('http://127.0.0.1:4174/?offline=1');
  await page.waitForFunction(() => window.buffet?.ready);
  assert.equal(await page.locator('#render-error').isVisible(), false);
  await page.screenshot({ path: root + 'artifacts/initial.png', fullPage: true });
  const mid = await page.evaluate(() => window.buffet.advance(125));
  assert.equal(mid.phase, 'training');
  await page.screenshot({ path: root + 'artifacts/browser-preview.png', fullPage: true });
  const data = await page.evaluate(() => window.buffet.snapshot());
  await writeFile(root + 'artifacts/stage-preview.png', Buffer.from(data.split(',')[1], 'base64'));
  const complete = await page.evaluate(() => window.buffet.advance(175));
  assert.equal(complete.phase, 'complete');
  assert.equal(await page.locator('#train-again').isDisabled(), false);
  await page.locator('#reward-2').fill('1');
  await page.locator('#train-again').click();
  assert.equal(await page.evaluate(() => window.buffet.simulation.phase), 'training');
  await page.locator('#learning').uncheck();
  assert.equal(await page.evaluate(() => window.buffet.simulation.learning), false);
  await page.locator('#reset').click();
  assert.equal(await page.evaluate(() => window.buffet.simulation.time), 0);
  await page.locator('#new-seed').click();
  assert.notEqual(await page.evaluate(() => window.buffet.simulation.seed), 17);
  const downloadPromise = page.waitForEvent('download');
  await page.locator('#export').click();
  const download = await downloadPromise;
  assert.match(download.suggestedFilename(), /^fruit-buffet-seed-\d+\.json$/);
  await page.evaluate(() => window.buffet.setOffline(false));
  await page.locator('#record').click();
  await page.waitForFunction(() => document.getElementById('record').classList.contains('recording'));
  await page.waitForTimeout(700);
  const clipPromise = page.waitForEvent('download');
  await page.locator('#record').click();
  const clip = await clipPromise;
  assert.match(clip.suggestedFilename(), /\.(webm|mp4)$/);
  await clip.saveAs(root + 'artifacts/recording-smoke-test.webm');
  assert.ok((await stat(root + 'artifacts/recording-smoke-test.webm')).size > 2000);
  await page.evaluate(() => window.buffet.setOffline(true));
  await page.locator('summary').click();
  assert.equal(await page.locator('.method-grid').isVisible(), true);
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true, 'no mobile horizontal overflow');
  await page.screenshot({ path: root + 'artifacts/mobile-preview.png', fullPage: true });
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: WebGL, deterministic advance, controls, JSON export, video recording, methods, mobile layout, no console/request errors.');
} finally {
  if (browser) await browser.close();
  server.kill();
}
